#
# gnu make, openwatcom (host=linux,target=dos)
#

export INCLUDE=/opt/watcom/h
export PATH:=/opt/watcom/binl:$(PATH)
export WATCOM=/opt/watcom

#CLFLAGS=-bcl=dos4g
CLFLAGS=-bcl=pmodew

CPPFLAGS=-w4 -e25 -j -zp1 -zq -od -d2 -5r -i=./

all:
	wcl386 $(CPPFLAGS) $(CLFLAGS) src/main.c -fe=dosbin/unchallenge.exe
	wstrip unchallenge.exe
